### ISSUE TITLE
跟其他issue一样，返回空类型报错

### ISSUE THREAD

**Issue by gagadaxiao** [ReiiNoki/nonebot-plugin-kuma-san#3]
首先感谢这个nb机器人的喷3报幕项目。
我不懂程序，群友帮忙看的。
喷3是个网游，会新增武器和场地。一更新翻译文件里没有的武器或地图，（大意）返回时接不到东西就会报错，然后群友帮忙改了下model.py，加了个缺省项。这样游戏更新后，但是翻译对照文件还没及时更新的情况会返回default，至少消息能发出来了。不过新地图/武器会显示default。
model.py代码为：
class Bankara(object):
    def __init__(self, start, end, rule, stage1, stage2) -> None:
        self.start = start
        self.end = end
        self.rule = get_rule(rule)
        self.stage1 = translate(stage1)
        self.stage2 = translate(stage2)

    def to_string(self) -> str:
        return (self.start or default)  + ' - ' + (self.end or default) + ' ' + (self.rule or default) + '\n' + (self.stage1 or default) + ' ' + (self.stage2 or default)

class FestStage(object):
    def __init__(self, start, end, stage1, stage2, tricolor) -> None:
        self.start = start
        self.end = end
        self.stage1 = translate(stage1)
        self.stage2 = translate(stage2)
        self.tricolor = translate(tricolor)

    def to_string(self) -> str:
        return (self.start or default) + ' - ' + (self.end or default) + '\n' + (self.stage1 or default) + ' ' + (self.stage2 or default)

class Regular(object):
    def __init__(self, start, end, stage1, stage2) -> None:
        self.start = start
        self.end = end
        self.stage1 = translate(stage1)
        self.stage2 = translate(stage2)

    def to_string(self) -> str:
        
        return (self.start or default) + ' - ' + (self.end or default) + '\n' + (self.stage1 or default) + ' ' + (self.stage2 or default)

**Comment by ReiiNoki** [comment]
今天才看到很抱歉..谢谢大佬修改代码。我后面先把新武器和场地内容更新一下。
本来是去年随便写写的东西没想到真的有人拿去用了很感谢使用！

**Comment by ReiiNoki** [comment]
原来打算把这个输出改写成图片的，但是看了下教程写起来好麻烦就暂时搁置了，没想到这个去年随便写的东西还有人发issue（

**Comment by gagadaxiao** [comment]
以前喷2的报幕bot就是图片形式，类似官方app了。那个确实很不错。输出图片也确实很麻烦，我也不会python。总之感谢这个插件。能先更新下翻译文件的话非常感谢

**Comment by ReiiNoki** [comment]
喷2那个bot我有学习过，可惜我们写法和架构不太一样不好套用，而且输出图片还得再挂个Redis做缓存有点麻烦，qq的bot也不稳定经常被腾讯封控就放弃搞了，请问你们是bot是挂在哪里的？

明天更新一下...我还得找找这几个赛季都更了啥武器和场地（

**Comment by ReiiNoki** [comment]
已更新新加入的武器和场地信息，更新到新版本即可

**Comment by ReiiNoki** [comment]
这边问题解决了我就close了，有其他问题另开issue哈

**Comment by gagadaxiao** [comment]
谢谢。抱歉这几天事情比较忙没有及时回复。bot是挂的win server 2022，真寻bot，我这个号群比较少基本上是一个群专用，用了那个gocq的签名服务器就不会控了。
nb商店输出图片的例子有表情包制作插件，图片素材非常多，好像要用到一个imageutils什么的库，不知道能不能参考下

**Comment by gagadaxiao** [comment]
通过pip install nonebot_plugin_kuma_san得到的translate文件好像跟以前没有区别。。

**Comment by ReiiNoki** [comment]
我在pypi上传的JSON是新的...不然你把这个repo里的复制粘贴过去也可以，pypi我再去看一下

**Comment by ReiiNoki** [comment]
导出图片我后面有空整一整吧，我个人不是什么专业码农就是业余写一下，请多包涵

**Comment by ReiiNoki** [comment]
translate.py这个文件当然没有区别啊...我的中日文翻译文件都是在dict.json里面的，如果没有更新就不会有空类型出来了。方便的话也把我拉进群我看看吧。

**Comment by gagadaxiao** [comment]
可以可以 非常感谢 群741041417

**Comment by ReiiNoki** [comment]
大佬给个进群答案啊（

**Comment by gagadaxiao** [comment]
抱歉我不是群主我问下，稍等

**Comment by gagadaxiao** [comment]
答案是陈睿
